### PR TITLE
Add libsql_open_sync_with_config

### LINKED ISSUE #1561: Feature Request: Expose `sync_interval` parameter in libsql's C bindings
Currently, there is no exposed `sync_interval` parameter in libsql's C bindings, which limits the flexibility of custom implementations built from source when using libsql's embedded replicas.

It would be beneficial to expose a `sync_interval` parameter in the C bindings, similar to how it's implemented in the TypeScript/JavaScript client API for libSQL. This would allow C implementations to configure automatic periodic sync.

For reference, the TypeScript/JavaScript client API for libSQL allows setting a sync interval like so:

```typescript
const client = createClient({
  url: 'file:path/to/db-file.db',
  authToken: '...',
  syncUrl: '...',
  syncInterval: 60,
});
```

### PR DESCRIPTION
**Pull request by haaawk**
Expose interval sync in C bindings.

Fixes #1561

### CODE REVIEW

**Comment by penberg** [comment]
I am fine with this, but curious to know if we can make the API simpler with a `libsql_config` struct. Is that something we can easily use from Go, for example?

**Comment by haaawk** [comment]
> I am fine with this, but curious to know if we can make the API simpler with a `libsql_config` struct. Is that something we can easily use from Go, for example?

I would have to check. That would also require update to op-sqlite too.

**Comment by haaawk** [comment]
Let me know if this looks better @penberg

**Comment by haaawk** [comment]
I was able to switch go-libsql to use libsql_config and all the tests have passed

**Comment by haaawk** [comment]
I was able to switch go-libsql to use libsql_config and all the tests passed -> https://github.com/tursodatabase/go-libsql/pull/32

**Review by penberg — APPROVED** [review]

**Pull request merged**
