### PR TITLE
sqlite3-parser: replace debug! with trace!

### LINKED ISSUE #617: SQLite3 parser spams debug logs hard
Let's make this `trace` instead of `debug`:

```
2023-11-14T09:04:36.347505Z DEBUG sqlite3Parser: Reduce 105 [selectnowith ::= oneselect], pop back to state 36.
2023-11-14T09:04:36.347513Z DEBUG sqlite3Parser: ... then shift 'selectnowith', go to state 211
2023-11-14T09:04:36.347519Z DEBUG sqlite3Parser: Reduce 151 [orderby_opt ::=].
2023-11-14T09:04:36.347527Z DEBUG sqlite3Parser: ... then shift 'orderby_opt', go to state 376
2023-11-14T09:04:36.347533Z DEBUG sqlite3Parser: Reduce 165 [limit_opt ::=].
2023-11-14T09:04:36.347552Z DEBUG sqlite3Parser: ... then shift 'limit_opt', pending reduce Some(104)
2023-11-14T09:04:36.347559Z DEBUG sqlite3Parser: Reduce 104 [select ::= selectnowith orderby_opt limit_opt], pop back to state 36.
2023-11-14T09:04:36.347567Z DEBUG sqlite3Parser: ... then shift 'select', go to state 283
2023-11-14T09:04:36.347578Z DEBUG sqlite3Parser: Reduce 183 [upsert ::=].
2023-11-14T09:04:36.347585Z DEBUG sqlite3Parser: ... then shift 'upsert', pending reduce Some(181)
2023-11-14T09:04:36.347591Z DEBUG sqlite3Parser: Reduce 181 [cmd ::= with insert_cmd INTO xfullname idlist_opt select upsert], pop back to state 0.
2023-11-14T09:04:36.347600Z DEBUG sqlite3Parser: ... then shift 'cmd', pending reduce Some(2)
2023-11-14T09:04:36.347670Z DEBUG sqlite3Parser: Reduce 2 [cmdx ::= cmd], pop back to state 0.
2023-11-14T09:04:36.347680Z DEBUG sqlite3Parser: ... then shift 'cmdx', go to state 556
2023-11-14T09:04:36.347686Z DEBUG sqlite3Parser: Shift 'SEMI', pending reduce Some(380)
2023-11-14T09:04:36.347695Z DEBUG sqlite3Parser: Return. Stack=[cmdx SEMI]
2023-11-14T09:04:36.347702Z DEBUG sqlite3Parser: Input '$' with pending reduce 380
2023-11-14T09:04:36.347708Z DEBUG sqlite3Parser: Reduce 380 [ecmd ::= cmdx SEMI] without external action, pop back to state 0.
2023-11-14T09:04:36.347715Z DEBUG sqlite3Parser: ... then shift 'ecmd', go to state 1
2023-11-14T09:04:36.347722Z DEBUG sqlite3Parser: Reduce 376 [input ::= cmdlist] without external action, pop back to state 0.
2023-11-14T09:04:36.347978Z DEBUG sqlite3Parser: ... then shift 'input', pending reduce None```

### PR DESCRIPTION
**Pull request by pjhades**
Attempts to resolve #617

### CODE REVIEW

**Comment by MarinPostma** [comment]
I think it would be less intrusive to just filter them out by default here: https://github.com/tursodatabase/libsql/blob/main/libsql-server/src/main.rs#L504-L510

**Comment by penberg** [comment]
@MarinPostma I personally prefer the current patch because then there's the option to see the tracing if needed. But I'll let you decide which way to go because you're going to suffer more from the decision than me :)

**Comment by psarna** [comment]
I kind of like this approach too - these messages just look like trace-tier

**Comment by psarna** [comment]
... and we already pulled the whole source code inside our repo, so we might just as well get intrusive :sweat_smile:

**Comment by MarinPostma** [comment]
alright, the crowd has expressed their opinion 😄

**Review by MarinPostma — APPROVED** [review]

**Pull request merged**
