### PR TITLE
sqld: temp fix replica namespace doesnt exist

### PR DESCRIPTION
**Pull request by LucioFranco**
there is a bug where a primary will report that a valid
                           namespace doesn't exist when it does and causes the replicate to
                            destroy the namespace locally. For now the temp solution is to
                            ignore this error (still log it) and don't destroy the local
                          namespace data on the replica. This trades off storage space for
              returing 500s.

### CODE REVIEW

**Review by MarinPostma — APPROVED** [review]

**Review by haaawk — APPROVED** [review]

**Comment by penberg** [comment]
@haaawk @LucioFranco Please make sure there is an issue about the root cause bug too so we remember to fix it.

**Comment by haaawk** [comment]
https://github.com/tursodatabase/libsql/issues/1772

**Comment by haaawk** [comment]
I was hoping we could fix the root issue on the primary but this is a good start to mitigate the problem

**Comment by MarinPostma** [comment]
Maybe we should let the control plane eagerly create namespaces on replicas. That would make stuff easier for sqld

**Pull request merged**
