### PR TITLE
Add Iterator and IntoIterator traits for Rows type

### PR DESCRIPTION
**Pull request by lpturmel**
This PR adds the implementation of the `Iterator` and `IntoIterator` traits to the Rows struct.

I don't know if currently there is a better way of doing something like this, but I wanted an API that looked a bit like what we have on the `libsql-client-rs` crate where you can interact with the returned rows as an iterator (in this case because rows is a Vec<Row>) like so:

```rust
    let rows = conn.query(
        "select * from hello",
        (),
    ).await.unwrap();
    let _ = rows
        .into_iter()
        .map(|r| from_row::<MyType>(&r.unwrap()).unwrap())
        .collect::<Vec<_>>();
```

Let me know what you guys think/what should be changed about the implementation.

### CODE REVIEW

**Comment by Horusiath** [comment]
Soon rows will enable async fetching (see #798). It also comes with an ability to convert Rows into Stream, with all operators available thanks to that conversion.

**Comment by SET001** [comment]
@Horusiath so now, with that PR, how to iterate rows?

**Comment by lpturmel** [comment]
I think this is how it is intended to be used:

```rust
use futures::StreamExt;
use libsql::de::from_row;
use libsql::Builder;

#[tokio::main]
async fn main() {
    // ... usual setup
    let todos = conn.query("SELECT * FROM todos", ()).await.unwrap();
    let stream = todos.into_stream();

    let todos = stream
        .map(|row| from_row::<Todo>(&row.unwrap()).unwrap())
        .collect::<Vec<_>>()
        .await;
}

```
This is using `StreamExt` from the `futures` crate.

**Comment by SET001** [comment]
@lpturmel thank you. this work just fine

**Pull request closed without merging**
