### PR TITLE
server: fix migration error hrana

### PR DESCRIPTION
**Pull request by LucioFranco**

### CODE REVIEW

**Review by glommer — COMMENTED** [review]
I suspect this will not be enough. I tried attach (which is not a migration), and got a dogshit error as well.

@avinassh  - this is the issue with ws.

**Comment by haaawk** [comment]
@MarinPostma please have a look at this PR

**Review by MarinPostma — APPROVED** [review]
you gotta love that fancy error handling 😄

**Comment by MarinPostma** [comment]
@glommer says it's not enough though

**Comment by haaawk** [comment]
Probably not enough but won't hurt

**Pull request merged**
