### PR TITLE
update cr-sqlite to v0.16.2

### PR DESCRIPTION
**Pull request by tantaman**
This updates to match https://github.com/vlcn-io/cr-sqlite/pull/399

I've conditional compilation based on whether or not we're in `libsql` keeping libsql up to date can be full automated. It previously required me doing a bunch of manual work and was slowing everything down to get changes over to the libsql side.

### CODE REVIEW

**Comment by penberg** [comment]
@psarna can we merge this?

**Comment by psarna** [comment]
@penberg as soon as conflicts are resolved - yeah

**Review by psarna — APPROVED** [review]

**Comment by tantaman** [comment]
Conflicts should be resolved.

I'm going to follow this up with a commit that adds cr-sqlite tests and build to CI so you all can start grabbing the correct version for inclusion in Turso builds. The one you currently grab does not include the `close_hook` and other libsql specific updates.

**Comment by tantaman** [comment]
Can we go ahead an merge this? I meant I'd follow up with a separate PR to add cr-sqlite to CI since it'd be easier to review separately.

**Pull request merged**
