### PR TITLE
pre-libSQL 0.2.3: merge with SQLite 3.44.0

### PR DESCRIPTION
**Pull request by psarna**
WARNING: currently breaks `crr` extension because of a new `xIntegrity` call added to `sqlite3_module`.

### CODE REVIEW

**Comment by psarna** [comment]
@MarinPostma @penberg  there's an unfortunate issue with `sqlite3_module` diverging, but also inevitable since we didn't decide to split to `libsql_module`. We kind of knew about the risk and still decided not to split to `libsql_module` to keep things simple, but now that `sqlite3_module` got extended maybe we should reconsider? We'll need a breaking change anyway. Alternatively we can put a few bytes worth of padding at the end of the `sqlite3_module` (e.g. 80) to account for future SQLite changes, and just keep appending libSQL interfaces past that.

**Comment by psarna** [comment]
Nvm, I'll add a `libsql_module` together with `libsql_create_module`, it's the only reasonable way to go.

**Comment by psarna** [comment]
@tantaman hi, we unfortunately hit a breaking API change moment, since we were too lazy to properly introduce a `libsql_module` struct next to `sqlite3_module`... I don't fully grasp how `sqlite-rs-embedded` is rebuilt/regenerated, can you help me port `crr` so that it works with the breaking change?

What changed is as follows: `xPreparedSql` is no longer part of `sqlite3_module`. Instead, there's a `libsql_create_module` call that accepts another parameter, a `libsql_module *` struct pointer, which has the definition of `xPreparedSql`. It should just be used instead of `sqlite3_create_module_v2`

**Comment by tantaman** [comment]
@psarna - sure. Want me to make that fix in a separate PR or provide you pointers on this one?

**Comment by psarna** [comment]
@tantaman whatever's easier! If you know exactly how to fix, then go ahead and I can learn from reviewing the PR itself (: thanks!

**Comment by glommer** [comment]
folks, `libsql_create_module` broke vss. I am trying to understand how to fix it. @tantaman it seems like you are the only user of this?

Long story short: for some reason I still don't completely understand, adding anything (even a `void *`) anywhere inside sqlite3_vtab, breaks sqlite-vss. I am trying to gain more context on how this is all used so I can propose a fix that works.

**Comment by tantaman** [comment]
@glommer I remember fixing this once before 🤔

What error are you seeing exactly? Just a compile error or issue at runtime?

Also is "vss" an alias for virtual table? Never heard the SQLite-vss term before

**Comment by glommer** [comment]
hey sorry, sqlite-vss is an extension: https://github.com/asg017/sqlite-vss (vector search, boomer!)
I haven't looked in details yet but my best guess is that it is somehow doing something that depends on the size of sqlite3_vtab being fixed. It breaks if I even add a void pointer to that structure. (Actually tagging @asg017 - do you have any idea why would sqlite-vss break by just adding a void pointer to `sqlite3_vtab` ?)

We have an error at runtime, quite a bizarre one, described here: https://github.com/tursodatabase/libsql/issues/865

**Comment by tantaman** [comment]
Maybe since sqlite-vss is compiled against the 3.40 headers instead of 3.44 (https://github.com/asg017/sqlite-vss/blob/8fc44301843029a13a474d1f292378485e1fdd62/vendor/get_sqlite.sh#L6)? Although I'd expect 3.44 to be backwards compatible so unlikely the bug but seems worth a shot to see if it makes a difference.

**Comment by glommer** [comment]
We found out what happened. Long story short, it's not safe to add any pointers to `sqlite3_vtab`. The pointers need to be in `sqlite3_module`. @avinassh is cooking up a solution and will post for review.

**Comment by tantaman** [comment]
Maybe because he extends the `vtab` struct with a custom one?

https://github.com/asg017/sqlite-vss/blob/8fc44301843029a13a474d1f292378485e1fdd62/src/sqlite-vss.cpp#L319-L351

I'm not experienced enough with C++ to know if this is a problem but seems like that could create an incompatible memory layout when the C++ object is compiled with a header with less fields (3.40) than the binary it is being loaded into (3.44).

ref #865

**Comment by glommer** [comment]
you are right, this is squarely our fault and we just made a mistake. When we tagged you we hadn't fully understood that yet, so it was more a plea to see if you had any idea.

We'll fix this on our side by moving those pointers somewhere else.

**Pull request merged**
