### PR TITLE
Update to v0.15.1 of cr-sqlite

### PR DESCRIPTION
**Pull request by tantaman**
This syncs the v0.15.1 release of `cr-sqlite` to libsql.

Todo:

- [x] Hook into the new cleanup routine https://github.com/tursodatabase/libsql/pull/219 (Done: https://github.com/tursodatabase/libsql/pull/434/commits/e583c6722f856942b339d45b8e1967c59bc9d66e)
- [x] Add valgrind test cases to check that new cleanup routine works as expected for cr-sqlite

Other / outside of this PR:
- Re-enable this extension for Turso.
    -  Note: if you auto-init this extension on connection create it will increase the time to create a new SQLite connection. Are Turso connections cached? Should we lazily init the extension? I've not measured this number but loading the extension involves preparing some statements which isn't cheap in SQLite.
- Complete cr-sqlite x Turso example -- https://github.com/vlcn-io/cr-sqlite/issues/376

### CODE REVIEW

**Comment by penberg** [comment]
@tantaman Looks good! There are some conflicts that prevent merging, though.

**Comment by tantaman** [comment]
@penberg - Once this is in, how can I go about getting it enabled on my turso instance? Or is it pretty simple to stand up sqld as if it were Turso on my own box?

**Comment by tantaman** [comment]
Conflicts resolved.

**Review by psarna — APPROVED** [review]

**Comment by tantaman** [comment]
I can rebase again and see what's up. Weird that `crr` files are conflicting 🤔

**Comment by psarna** [comment]
I ended up rebasing manually; we restructured the repo lately and moved the root directory to libsql-sqlite3, hence the huge conflicts

**Comment by tantaman** [comment]
closing in favor of: https://github.com/tursodatabase/libsql/pull/488

which uses the new directory layout.

**Pull request closed without merging**
